function Contenido(){
    return  <><h3>Composicion <a href="#">[editar]</a></h3>
    <hr/>
    <p>A su regreso a España desde <a href="#">Roma</a>  en el año 1583, Victoria fue nombrado por el rey <a href="#">Felipe II capellan</a>  personal de su hermana la emperatriz <a href="#">María de Austria y Portugal</a>  en el <a href="#">Convento de las Descalzas Reales</a>. La emperatriz se había retirado al convento tras la muerte de su esposo, el emperador <a href="#">Maximiliano II</a>, acompañada de su hija<a href=" #"> Margarita</a>.</p>

<p>María muere en febrero de 1603, y Victoria compone en su memoria una <a href="#">misa de réquiem</a>, el Officium Deffunctorum, considerada por los especialistas como su obra cumbre y definida por el propio Victoria en la dedicatoria de su publicación, en 1605, <a href="">como su canto del cisne</a>.</p>

<p>Se ha escrito mucho acerca de la utilización de esta pieza en las diferentes exequias llevadas a cabo tras la muerte de la Emperatriz. Su entierro en el propio convento el 1 de marzo; las exequias solemnes celebradas en el mismo sitio el 18 por la tarde y 19 por la mañana; las civiles organizadas por la ciudad de Madrid a continuación, 19 por la tarde y 20 por la mañana; las Reales, celebradas en la corte, por esos años situada en Valladolid, comenzando el 21 de marzo, bajo la dirección musical del <a href="">Maestro de capilla</a> de la Real Capilla, <a href="">Mateo Romero</a>; y las celebradas poco después por la <a href=""> Compañía de Jesús</a>, muy allegada a la Emperatriz, en Madrid el 21 y 22 de abril. No hay ninguna fuente de la época que de pistas sobre el uso o no de esta música en tales ocasiones, salvo la propia dedicatoria de Victoria en su edición, que afirma publicarse como recuerdo de tal momento, única pista que tenemos al respecto. Por otro lado, la propia factura de la publicación de 1605, con el escudo de los Austrias presidiendo la portada, tiene mucho más que ver con las ediciones o copias que se hacían para perpetuar la memoria de una ocasión con la música usada para ella, 
que con las otras publicaciones del propio Victoria.1​</p>

<p>La inclusión del <a href=""> Responsorio</a>, cuyo uso habitual era acompañar el momento de la absolución durante la ceremonia del enterramiento, hace sospechar que, al menos parcialmente, pueda haber sido usada en las exequias y enterramiento del 1 de marzo; siquiera esta sección. Se ha especulado si a Victoria no le hubiera dado tiempo a escribir más, o si tal vez hubiera comenzado previamente, al ver aproximarse el fin de la Emperatriz, pero no hay nada constatable al respecto. Y se considera como su uso más probable en forma completa (junto con los añadidos de música necesarios para la liturgia del día, que incluye oficios, y otras dos misas) la siguiente celebración en Las Descalzas, la del 18-19 de marzo. Una razón extra para ello es la presencia de 4 cantores de refuerzo, que vinieron de Toledo para la ocasión, los cuales, junto con los 8 canónigos encargados del canto en el convento, sumarían justamente los 12 cantores necesarios (de ser dos por parte) para esta composición a 6 voces. Más improbable parece ser el caso de Valladolid, y de las civiles de Madrid. Y ninguna pista tenemos realmente sobre las jesuitas. En todo caso, todo son conjeturas, si bien bastante plausibles.2​</p>

<p>La publicación de la obra en 1605, en la Imprenta Real, en Madrid, fue dedicada a la hija de la emperatriz, la princesa <a href="">Margarita</a>, también profesa en el mismo convento.</p>
    </>;
}
export default Contenido