function Contenido2(){
    return  <><h3>Estructura <a href="#">[editar]</a></h3>
    <hr/>
    <p>El Officium Defunctorum consta de 10 secciones. Además de los movimientos propios de la misa de réquiem, Victoria agregó tres piezas adicionales: Taedet animam meam, la segunda lección de los maitines de Difuntos, el motete Versa est in luctum, y un responsorio. Las dos primeras secciones mencionadas toman su texto del <a href="">libro de Job</a>. Se incluyen todas las secciones propias de la misa de réquiem, salvo el Tractus y el Dies Irae,</p>

<p>Mientras la sección Taedet animam meam y el motete Versa est in luctum son composiciones libres, el resto de las secciones combinan el <a href=""> canto llano</a> propio del canto gregoriano, monódico y de ritmo libre, con el canto polifónico, estructurado sobre un <a href="">cantus firmus</a>, es decir una melodía preexistente. El canto llano marca las divisiones de la obra, indicando el comienzo de una sección o introduciendo una parte dentro de la misma.</p>

<p>Sobre la estructura de la pieza, conviene tener en cuenta que el criterio de ordenación en la publicación de Victoria no corresponde totalmente con su uso litúrgico.3​ La Lección de <a href=""> Maitines</a> Tædet animam meam está publicada originalmente al final de la colección, a modo casi de apéndice, aunque por tradición, en tiempos modernos se suele ejecutar a modo de apertura, por lo que figura aquí en primer lugar, conforme a esta costumbre actual. También porque corresponde a un oficio que se celebra temprano el día correspondiente, antes de la misa. El motete, Versa est in luctum, no tiene un lugar definido en la liturgia. Probablemente iría intercalado entre las secciones propias de la misa originalmente (como hace por ejemplo <a href=""> Juan Vásquez </a> en su Agenda Defunctorum), aunque es frecuente hoy en día interpretarlo después de esta, donde figura en la publicación. Así mismo, el responsorio Libera me era utilizado habitualmente en la absolución durante la ceremonia del enterramiento, tras la misa de difuntos (si sucede a continuación de esta), si bien puede tener cabida también en otros momentos de los oficios de difuntos, o de los oficios del día de Todos los Difuntos (2 de noviembre). No estaba esta obra originalmente concebida como una unidad interpretativa, como ocurre con todas las misas del período, pues había numerosos cantos en gregoriano, u otras piezas en polifonía, intercaladas entre los movimientos de la misa, y otra gran cantidad de música acompañando en los oficios correspondientes a las dos piezas que corresponden a estos.​</p>

    </>;
}
export default Contenido2